// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF_ITI_DB_ReverseEngineer.Models;

[Keyless]
[Table("studentAudit")]
public partial class StudentAudit
{
    [Column("serverUserName")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ServerUserName { get; set; }

    [Column("insertionDate")]
    public DateOnly? InsertionDate { get; set; }

    [Column("note")]
    public string? Note { get; set; }
}