// <auto-generated />
using System;
using ECommerce.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306070457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.DAL.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ECommerce.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("ECommerce.DAL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 5,
                            Description = "Gaming laptop",
                            ExpiryDate = new DateOnly(2028, 1, 1),
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 10,
                            Description = "Android phone",
                            ExpiryDate = new DateOnly(2027, 6, 1),
                            IsDeleted = false,
                            Name = "Smartphone",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Count = 15,
                            Description = "Wireless headphones",
                            ExpiryDate = new DateOnly(2027, 3, 1),
                            IsDeleted = false,
                            Name = "Headphones",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Count = 7,
                            Description = "Fitness watch",
                            ExpiryDate = new DateOnly(2027, 8, 1),
                            IsDeleted = false,
                            Name = "Smart Watch",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Count = 20,
                            Description = "Cotton t-shirt",
                            ExpiryDate = new DateOnly(2026, 12, 1),
                            IsDeleted = false,
                            Name = "T-Shirt",
                            Price = 300m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Count = 12,
                            Description = "Blue jeans",
                            ExpiryDate = new DateOnly(2027, 5, 1),
                            IsDeleted = false,
                            Name = "Jeans",
                            Price = 800m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Count = 6,
                            Description = "Winter jacket",
                            ExpiryDate = new DateOnly(2027, 11, 1),
                            IsDeleted = false,
                            Name = "Jacket",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Count = 9,
                            Description = "Running shoes",
                            ExpiryDate = new DateOnly(2027, 9, 1),
                            IsDeleted = false,
                            Name = "Sneakers",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Count = 10,
                            Description = "Learn C#",
                            ExpiryDate = new DateOnly(2029, 1, 1),
                            IsDeleted = false,
                            Name = "C# Book",
                            Price = 500m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Count = 8,
                            Description = "Spring Boot guide",
                            ExpiryDate = new DateOnly(2029, 6, 1),
                            IsDeleted = false,
                            Name = "Java Book",
                            Price = 600m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Count = 5,
                            Description = "Machine Learning basics",
                            ExpiryDate = new DateOnly(2029, 3, 1),
                            IsDeleted = false,
                            Name = "Data Science Book",
                            Price = 750m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Count = 4,
                            Description = "DSA concepts",
                            ExpiryDate = new DateOnly(2029, 5, 1),
                            IsDeleted = false,
                            Name = "Algorithms Book",
                            Price = 650m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Count = 3,
                            Description = "800W microwave",
                            ExpiryDate = new DateOnly(2028, 2, 1),
                            IsDeleted = false,
                            Name = "Microwave",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Count = 2,
                            Description = "Double door fridge",
                            ExpiryDate = new DateOnly(2028, 7, 1),
                            IsDeleted = false,
                            Name = "Refrigerator",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Count = 4,
                            Description = "Automatic washer",
                            ExpiryDate = new DateOnly(2028, 4, 1),
                            IsDeleted = false,
                            Name = "Washing Machine",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Count = 3,
                            Description = "1.5 HP AC",
                            ExpiryDate = new DateOnly(2028, 9, 1),
                            IsDeleted = false,
                            Name = "Air Conditioner",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Count = 14,
                            Description = "FIFA standard ball",
                            ExpiryDate = new DateOnly(2027, 2, 1),
                            IsDeleted = false,
                            Name = "Football",
                            Price = 400m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Count = 5,
                            Description = "Professional racket",
                            ExpiryDate = new DateOnly(2027, 10, 1),
                            IsDeleted = false,
                            Name = "Tennis Racket",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Count = 6,
                            Description = "Carbon fiber padel",
                            ExpiryDate = new DateOnly(2027, 12, 1),
                            IsDeleted = false,
                            Name = "Padel Racket",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Count = 8,
                            Description = "10kg pair",
                            ExpiryDate = new DateOnly(2027, 4, 1),
                            IsDeleted = false,
                            Name = "Dumbbells",
                            Price = 900m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.DAL.Product", b =>
                {
                    b.HasOne("ECommerce.DAL.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ECommerce.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ECommerce.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ECommerce.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.DAL.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
