// <auto-generated />
using System;
using ECommerce.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.DAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260314122005_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("ECommerce.DAL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 5,
                            Description = "Gaming laptop",
                            ExpiryDate = new DateOnly(2028, 1, 1),
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 10,
                            Description = "Android phone",
                            ExpiryDate = new DateOnly(2027, 6, 1),
                            IsDeleted = false,
                            Name = "Smartphone",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Count = 15,
                            Description = "Wireless headphones",
                            ExpiryDate = new DateOnly(2027, 3, 1),
                            IsDeleted = false,
                            Name = "Headphones",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Count = 7,
                            Description = "Fitness watch",
                            ExpiryDate = new DateOnly(2027, 8, 1),
                            IsDeleted = false,
                            Name = "Smart Watch",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Count = 20,
                            Description = "Cotton t-shirt",
                            ExpiryDate = new DateOnly(2026, 12, 1),
                            IsDeleted = false,
                            Name = "T-Shirt",
                            Price = 300m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Count = 12,
                            Description = "Blue jeans",
                            ExpiryDate = new DateOnly(2027, 5, 1),
                            IsDeleted = false,
                            Name = "Jeans",
                            Price = 800m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Count = 6,
                            Description = "Winter jacket",
                            ExpiryDate = new DateOnly(2027, 11, 1),
                            IsDeleted = false,
                            Name = "Jacket",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Count = 9,
                            Description = "Running shoes",
                            ExpiryDate = new DateOnly(2027, 9, 1),
                            IsDeleted = false,
                            Name = "Sneakers",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Count = 10,
                            Description = "Learn C#",
                            ExpiryDate = new DateOnly(2029, 1, 1),
                            IsDeleted = false,
                            Name = "C# Book",
                            Price = 500m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Count = 8,
                            Description = "Spring Boot guide",
                            ExpiryDate = new DateOnly(2029, 6, 1),
                            IsDeleted = false,
                            Name = "Java Book",
                            Price = 600m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Count = 5,
                            Description = "Machine Learning basics",
                            ExpiryDate = new DateOnly(2029, 3, 1),
                            IsDeleted = false,
                            Name = "Data Science Book",
                            Price = 750m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Count = 4,
                            Description = "DSA concepts",
                            ExpiryDate = new DateOnly(2029, 5, 1),
                            IsDeleted = false,
                            Name = "Algorithms Book",
                            Price = 650m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Count = 3,
                            Description = "800W microwave",
                            ExpiryDate = new DateOnly(2028, 2, 1),
                            IsDeleted = false,
                            Name = "Microwave",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Count = 2,
                            Description = "Double door fridge",
                            ExpiryDate = new DateOnly(2028, 7, 1),
                            IsDeleted = false,
                            Name = "Refrigerator",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Count = 4,
                            Description = "Automatic washer",
                            ExpiryDate = new DateOnly(2028, 4, 1),
                            IsDeleted = false,
                            Name = "Washing Machine",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Count = 3,
                            Description = "1.5 HP AC",
                            ExpiryDate = new DateOnly(2028, 9, 1),
                            IsDeleted = false,
                            Name = "Air Conditioner",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Count = 14,
                            Description = "FIFA standard ball",
                            ExpiryDate = new DateOnly(2027, 2, 1),
                            IsDeleted = false,
                            Name = "Football",
                            Price = 400m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Count = 5,
                            Description = "Professional racket",
                            ExpiryDate = new DateOnly(2027, 10, 1),
                            IsDeleted = false,
                            Name = "Tennis Racket",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Count = 6,
                            Description = "Carbon fiber padel",
                            ExpiryDate = new DateOnly(2027, 12, 1),
                            IsDeleted = false,
                            Name = "Padel Racket",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Count = 8,
                            Description = "10kg pair",
                            ExpiryDate = new DateOnly(2027, 4, 1),
                            IsDeleted = false,
                            Name = "Dumbbells",
                            Price = 900m
                        });
                });

            modelBuilder.Entity("ECommerce.DAL.Product", b =>
                {
                    b.HasOne("ECommerce.DAL.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.DAL.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
